input_h: 256
input_w: 256
n_channels: 1

model_class: model.baseline_unet.UNetBaseline
preprocessor_class: model.pre_processing.PreProcessor
dataset_class: dataset.dataset_camus.CAMUSDataset

data_handler:
  batch_size: 8
  split_ratio: 0.9
  to_fit: True
  shuffle: True
  seed: 101
  camus_dataset:
    target_dataset_name: "CAMUS"
    dataset_dir: "/content/training"
    dataset_features:
      age: [18, 100]
      sex: ["M", "F"]
      stage: ["ES", "ED"]
      image_quality: ["Poor", "Medium", "Good"]
      view: ["4CH"]
  echonet_dynamic_dataset:
    target_dataset_name: "echo_net_dynamic"
    dataset_dir: "D:/AIMedic/FinalProject_echocardiogram/echoC_Dataset/echonet_dynamic/EchoNet-Dynamic"
    dataset_features:
      stage: ["ES", "ED"]
      view: ["4CH"]

model:
  name: "baseline-unet"
  optimizer:
    type: "adam"
    initial_lr: 0.0001
  loss_type: "binary_crossentropy"
  metrics: ["dice_coef", "iou", "acc"]
  inference_threshold: 0.5

pre_process:
  format: "gray_scale"
  max: 255
  min: 0
  do_resizing: True
  do_normalization: True
  augmentation:
    rotation_proba: 0.5
    rotation_range: 45
    flip_proba: 0.5

trainer:
  epochs: 30
  callbacks:
    checkpoints:
      save_freq: "epoch"
      evaluation_metrics: ["val_loss", "val_dice_coef"]
      monitor: "val_loss"  # set null if you want to checkpoint in every epoch
    tensorboard:
      update_freq: "epoch"
  export:
    metric: "val_loss"
    mode: "min"
  mlflow:
    tracking_uri: '/content/drive/MyDrive/AIMedic - Moazed/Experiments/MLFlow Experiments'
    experiment_name: 'echo_seg'
#    run_name: 'baseline-0'
