input_h: 128
input_w: 128
n_channels: 1

model_class: model.unet.UNet
preprocessor_class: model.pre_processing.PreProcessor
dataset_class: dataset.dataset_camus.CAMUSDataset

data_handler:
  target_dataset_name: "CAMUS"
  dataset_dir: "/content/training"
  batch_size: 8
  split_ratio: 0.9
  to_fit: True
  shuffle: True
  seed: 101

model:
  name: "unet"
  optimizer:
    type: "adam"
    initial_lr: 0.001
  loss_type: "binary_crossentropy"
  metrics: ["dice_coef", "iou", "acc"]

pre_process:
  format: "gray_scale"
  max: 255
  min: 0
  normalization: True
  augmentation:
    rotation_range: 0

trainer:
  epochs: 100
#  checkpoints_dir: "./checkpoints"
#  logs_dir: "./logs"
  callbacks:
    checkpoints:
      save_freq: "epoch"
      evaluation_metrics: ["val_loss", "val_dice_coef"]
    tensorboard:
      update_freq: "epoch"
  export:
    metric: "val_loss"
    mode: "min"
  mlflow:
    tracking_uri: 'echotrain/config'
    experiment_name: 'unet'
