input_h: 128
input_w: 128
n_channels: 1

data_handler:
  target_dataset_name: "CAMUS"
  dataset_class_name: "CAMUSDataset"
  dataset_dir: "D:/AIMedic/FinalProject_echocardiogram/echoC_Dataset/CAMUS/training"
  batch_size: 100
  n_channels: n_channels
  split_ratio: 0.9
  to_fit: True
  shuffle: True
  seed: None

model:
  name: "unet"
  optimizer:
    type: "adam"
    initial_lr: 0.001
  loss_type: "binary_crossentropy"
  metrics: ["dice", "2d_hausdorff", "iou"]

pre_process:
  normalization: True
  augmentation:
    rotation_range: 0

trainer:
  epochs: 100
#  checkpoints_dir: "./checkpoints"
#  logs_dir: "./logs"
  callbacks:
    checkpoints:
      save_freq: "epoch"
    tensorboard:
      update_freq: "epoch"

