input_h: 128
input_w: 128
n_channels: 1

model_class: model.unet.UNet
preprocessor_class: model.pre_processing.PreProcessor
dataset_class: dataset.dataset_camus.CAMUSDataset

data_handler:
  target_dataset_name: "CAMUS"
  dataset_class_name: "CAMUSDataset"
  dataset_dir: "D:/AIMedic/FinalProject_echocardiogram/echoC_Dataset/CAMUS/training"
  batch_size: 100
  split_ratio: 0.9
  to_fit: True
  shuffle: True
  seed: 101

model:
  name: "unet"
  optimizer:
    type: "adam"
    initial_lr: 0.001
  loss_type: "dice_coef_loss"
  metrics: ["dice_coef", "iou", "acc", '2d_hausdorff']

pre_process:
  normalization: True
  augmentation:
    rotation_range: 0

trainer:
  epochs: 100
#  checkpoints_dir: "./checkpoints"
#  logs_dir: "./logs"
  callbacks:
    checkpoints:
      save_freq: "epoch"
      evaluation_metrics: ["val_loss", "val_accuracy"]
    tensorboard:
      update_freq: "epoch"
  export:
    metric: "val_loss"
    mode: "min"


